//! Coverage inventory (the repair tranche's machine-enforced map):
//! the §10.4 outcome → vector map is GENERATED from the builders
//! (harvested off every vector's `expected` tree) and committed as
//! `coverage/outcomes-map.json` (drift-gated like the vectors), and
//! the uncovered set is pinned SHRINK-ONLY — covering an outcome
//! requires deleting its pin entry, and losing coverage of a covered
//! outcome fails the suite. A vector's `surfaces` array is an
//! ANNOTATION (declared applicability), never execution: the map's
//! `executed_surfaces` rider names what actually RUNS the corpus —
//! the two Rust reference implementations, the Chromium browser
//! lane, and the three storage-OS lanes — and each lane's run set
//! is pinned to `coverage/lane-manifests.json`.
//!
//! The §13.3 obligation ledger is the hand-transcribed sibling
//! (`coverage/obligations-13-3.json`), enforced by
//! `obligations_ledger_is_sound`: every entry's `quote` appears
//! verbatim inside §13.3, entry line-ranges COVER the whole section
//! (completeness — a spec edit that adds an obligation breaks the
//! coverage), every named vector exists, and status is consistent
//! with the vector list.

use crate::outcomes::OUTCOMES;
use crate::vector::Vector;
use serde_json::{json, Value as Json};
use std::collections::BTreeMap;

/// Every minted vector, one list (the mint bin's assembly order).
pub fn all_vectors() -> Vec<Vector> {
    let mut all = crate::tranche::tranche();
    all.extend(crate::corpus::corpus());
    all.extend(crate::corpus_fold::corpus_fold());
    all.extend(crate::corpus_recovery::corpus_recovery());
    all.extend(crate::corpus_edge::corpus_edge());
    all.extend(crate::corpus_migration::corpus_migration());
    all.extend(crate::corpus_status::corpus_status());
    all.extend(crate::corpus_erase::corpus_erase());
    all.extend(crate::corpus_time::corpus_time());
    all.extend(crate::corpus_ctrl::corpus_ctrl());
    all.extend(crate::corpus_budget::corpus_budget());
    all.extend(crate::corpus_audit::corpus_audit());
    all
}

/// Collect every string under an `"outcome"` key anywhere in the
/// vector's EXPECTED tree (per_item rows, per_record rows, erase
/// outcomes rows, negative arms — inputs are never scanned).
fn harvest(node: &Json, into: &mut Vec<String>) {
    match node {
        Json::Object(m) => {
            if let Some(Json::String(o)) = m.get("outcome") {
                into.push(o.clone());
            }
            for v in m.values() {
                harvest(v, into);
            }
        }
        Json::Array(a) => {
            for v in a {
                harvest(v, into);
            }
        }
        _ => {}
    }
}

/// The §10.4 map: outcome → sorted vector names whose expected tree
/// asserts it.
pub fn outcome_map() -> BTreeMap<&'static str, Vec<String>> {
    let mut map: BTreeMap<&'static str, Vec<String>> =
        OUTCOMES.iter().map(|o| (*o, Vec::new())).collect();
    for v in all_vectors() {
        let mut found = Vec::new();
        harvest(&v.to_json()["expected"], &mut found);
        found.sort();
        found.dedup();
        for o in found {
            let slot = map
                .get_mut(o.as_str())
                .unwrap_or_else(|| panic!("{}: outcome {o:?} outside §10.4", v.name));
            slot.push(v.name.clone());
        }
    }
    for names in map.values_mut() {
        names.sort();
    }
    map
}

/// The committed `coverage/outcomes-map.json` content.
pub fn outcomes_map_file() -> String {
    let map = outcome_map();
    let covered: serde_json::Map<String, Json> = map
        .iter()
        .filter(|(_, v)| !v.is_empty())
        .map(|(o, v)| (o.to_string(), json!(v)))
        .collect();
    let uncovered: Vec<&str> = map
        .iter()
        .filter(|(_, v)| v.is_empty())
        .map(|(o, _)| *o)
        .collect();
    let doc = json!({
        "$comment": "GENERATED by the core mint bin — the §10.4 outcome → vector map, harvested from every vector's expected tree. Edit builders, never this file; the drift gate pins it.",
        "executed_surfaces": ["rust-core", "rust-reducer", "browser-chromium", "storage-macos", "storage-linux", "storage-windows"],
        "surface_annotation_note": "A vector's `surfaces` array declares §13.2 applicability; execution is what the named lanes actually run. Executing today: the two Rust reference implementations, the Chromium browser lane (WebCrypto semantics + the f13 IndexedDB/Web-Locks substrate; run set pinned to lane-manifests.json), and the 3-OS portable-storage lane (real files, flush + atomic replacement, cross-process locks; same pin). native-crypto remains annotation-only (the Rust suites execute those primitives natively); Gate-B concerns stay out per execution-lanes-plan.md.",
        "covered": covered,
        "uncovered": uncovered,
    });
    let mut s = serde_json::to_string_pretty(&doc).expect("map serializes");
    s.push('\n');
    s
}

/// The committed `coverage/lane-manifests.json` content: the exact
/// per-lane vector-name run sets BOTH execution-lane drivers pin
/// against (review R5 — a mutable annotation alone cannot shrink a
/// lane run).
pub fn lane_manifests_file() -> String {
    let mut browser: Vec<String> = Vec::new();
    let mut storage: Vec<String> = Vec::new();
    for v in all_vectors() {
        let file = format!("f{:02}-{}.json", v.family, v.name);
        if v.surfaces.iter().any(|s| s == "browser") {
            browser.push(file.clone());
        }
        if v.surfaces.iter().any(|s| s.starts_with("storage-")) {
            storage.push(file);
        }
    }
    browser.sort();
    storage.sort();
    let doc = json!({
        "$comment": "GENERATED by the core mint bin — the exact lane run sets (review R5). The browser driver and the storage lane FAIL unless they run exactly these files; the surfaces suite pins every annotation to the §13.2 requirement, so a builder edit cannot silently shrink a lane.",
        "browser": browser,
        "storage": storage,
    });
    let mut s = serde_json::to_string_pretty(&doc).expect("manifests serialize");
    s.push('\n');
    s
}

/// §10.4 outcomes with NO exercising vector — 12 of 59 after the
/// D-203 cheap-gap batch closed ten (the five scope axes, no-grant,
/// no-flow, op-unknown, unknown-version, lineage-gen). Every entry
/// is an EXPLICIT Gate-B deferral under the ratified scope line
/// (D-203): the reason names the machinery it waits on, and the
/// inventory's `gate_b_deferrals` section must list exactly this
/// set (`obligations_ledger_is_sound` ties them). Shrink-only:
/// adding coverage deletes the entry here AND there; a regression
/// fails.
pub const UNCOVERED_10_4: &[&str] = &[
    // The f12 edge audit lane (lock-loser audited read, audit-budget
    // exhaustion).
    "audit-unavailable",
    // Certificate renewal is fail-closed in P1 v1 — the superseding
    // path cannot arise until the renewal machinery lands.
    "cert-superseded",
    // The §7.6 class table + sensitivity-ceiling machinery.
    "class-ceiling",
    "class-excluded",
    // The generation machine (gen ≠ 1 is fail-closed wholesale as
    // `lineage-gen`; the gen-opening arithmetic never runs in v1).
    "gen-first-op",
    // Issuer feed chains (the f9 sagas).
    "issuer-fork",
    "issuer-gap",
    // The provenance-ceiling tenant axis (hosted-plane machinery
    // beyond the vectored control ceiling).
    "provenance-ceiling",
    // The C3-prime competition arm (recovery sagas).
    "recovery-competition",
    // The journal adopted-erasure composite (f11 transfer sagas).
    "source-erased",
    // Fault injection — the execution lanes' Gate-B tail.
    "storage-io",
    // Recovery storage adoption is fail-closed in P1 v1 —
    // storage-orphaned is unreachable until it lands.
    "storage-orphaned",
];

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed outcomes map matches the generator byte-exactly
    /// (the coverage instance of the vector drift gate).
    #[test]
    fn committed_outcomes_map_matches_generator() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("coverage")
            .join("outcomes-map.json");
        let committed = std::fs::read_to_string(&path)
            .unwrap_or_else(|_| panic!("{} not minted", path.display()));
        assert_eq!(
            committed,
            outcomes_map_file(),
            "outcomes-map.json drifted from the builders"
        );
    }

    /// The committed lane manifests match the generator byte-exactly.
    #[test]
    fn committed_lane_manifests_match_generator() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("coverage")
            .join("lane-manifests.json");
        let committed = std::fs::read_to_string(&path)
            .unwrap_or_else(|_| panic!("{} not minted", path.display()));
        assert_eq!(
            committed,
            lane_manifests_file(),
            "lane-manifests.json drifted from the builders"
        );
    }

    /// The shrink-only pin: the derived uncovered set equals the
    /// declared one exactly, in both directions.
    #[test]
    fn uncovered_outcomes_pinned_shrink_only() {
        let map = outcome_map();
        let derived: Vec<&str> = map
            .iter()
            .filter(|(_, v)| v.is_empty())
            .map(|(o, _)| *o)
            .collect();
        let mut pinned: Vec<&str> = UNCOVERED_10_4.to_vec();
        pinned.sort_unstable();
        assert_eq!(
            derived, pinned,
            "uncovered §10.4 outcomes moved: new coverage must delete its pin entry; \
             a regression must be fixed, not re-pinned"
        );
    }

    /// Every harvested outcome string is §10.4 vocabulary (the
    /// harvest panics inline; this pins the invariant as a test).
    #[test]
    fn harvested_outcomes_are_vocabulary() {
        let _ = outcome_map();
    }

    /// The §13.3 obligation ledger: quotes verbatim, line-ranges
    /// covering the WHOLE section, vectors real, statuses coherent.
    #[test]
    fn obligations_ledger_is_sound() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("..");
        let spec = std::fs::read_to_string(root.join("owner-plane-d0a-spec.md")).unwrap();
        // The §13.3 slice, exclusive of its heading and terminator.
        let start = spec.find("### 13.3 Families").expect("§13.3 present");
        let end = spec[start..]
            .find("\n## 14.")
            .map(|i| start + i)
            .expect("§14 terminates §13.3");
        let section = &spec[start..end];
        let lines: Vec<&str> = section.lines().collect();

        let ledger: Json = serde_json::from_str(
            &std::fs::read_to_string(root.join("coverage").join("obligations-13-3.json")).unwrap(),
        )
        .unwrap();
        let names: std::collections::BTreeSet<String> =
            all_vectors().into_iter().map(|v| v.name).collect();

        let entries = ledger["obligations"].as_array().expect("obligations");
        assert!(!entries.is_empty());
        let mut covered = vec![false; lines.len()];
        let mut ids = std::collections::BTreeSet::new();
        for e in entries {
            let id = e["id"].as_str().expect("id");
            assert!(ids.insert(id.to_string()), "duplicate obligation id {id}");
            // Verbatim quote pin: the transcription cannot drift
            // from the spec text it claims to cover.
            let quote = e["quote"].as_str().expect("quote");
            assert!(
                section.contains(quote),
                "{id}: quote not verbatim in §13.3: {quote:?}"
            );
            // Line coverage (1-indexed within the section).
            let lr = e["lines"].as_array().expect("lines");
            let (a, b) = (
                lr[0].as_u64().expect("start") as usize,
                lr[1].as_u64().expect("end") as usize,
            );
            assert!(a >= 1 && a <= b && b <= lines.len(), "{id}: line range");
            for c in covered.iter_mut().take(b).skip(a - 1) {
                *c = true;
            }
            // Vector references + status coherence.
            let vs = e["vectors"].as_array().expect("vectors");
            for v in vs {
                let n = v.as_str().expect("vector name");
                assert!(names.contains(n), "{id}: unknown vector {n:?}");
            }
            let status = e["status"].as_str().expect("status");
            match status {
                "vectored" | "partial" => {
                    assert!(!vs.is_empty(), "{id}: {status} with no vectors")
                }
                // pending = unvectored debt; code-test = executed by
                // named Rust unit tests (a real execution surface,
                // unlike surface annotations) with no vector shape;
                // structural = non-obligation section furniture.
                "pending" | "structural" => {
                    assert!(vs.is_empty(), "{id}: {status} yet lists vectors")
                }
                "code-test" => {
                    assert!(vs.is_empty(), "{id}: code-test yet lists vectors");
                    assert!(
                        e["tests"].as_array().is_some_and(|t| !t.is_empty()),
                        "{id}: code-test must name its tests"
                    );
                }
                other => panic!("{id}: unknown status {other:?}"),
            }
        }
        // Completeness: every line of §13.3 is claimed by some
        // obligation (blank lines included — they belong to the
        // obligation whose prose they separate).
        let holes: Vec<usize> = covered
            .iter()
            .enumerate()
            .filter(|(_, c)| !**c)
            .map(|(i, _)| i + 1)
            .collect();
        assert!(
            holes.is_empty(),
            "§13.3 lines unclaimed by any obligation: {holes:?}"
        );
        // The executed-surface honesty rider (both lanes delivered
        // 2026-07-15; review R8.7 caught the stale two-surface
        // claim persisting past the deliveries).
        assert_eq!(
            ledger["executed_surfaces"],
            json!([
                "rust-core",
                "rust-reducer",
                "browser-chromium",
                "storage-macos",
                "storage-linux",
                "storage-windows"
            ]),
            "the ledger must state the honest executed surfaces"
        );
        // The D-203 Gate-B deferral record must exist and must list
        // EXACTLY the uncovered §10.4 outcomes (deferral is a
        // decision, not drift).
        let def = &ledger["gate_b_deferrals"];
        let listed: Vec<&str> = def["outcomes"]
            .as_array()
            .expect("gate_b_deferrals.outcomes")
            .iter()
            .map(|v| v.as_str().expect("outcome name"))
            .collect();
        assert_eq!(
            listed,
            UNCOVERED_10_4.to_vec(),
            "the deferral record must match the uncovered set exactly"
        );
        assert!(
            def["sagas"].as_array().is_some_and(|a| !a.is_empty()),
            "the deferred ceremony sagas must be named"
        );
    }
}
